### PR TITLE
Add a partial OIDC mock based on OpenAPI artifacts

### PR DESCRIPTION
**Pull request by rquinio1A**
### Description

My use case for creating this mock is a Quarkus backend application that receives HTTP requests with access tokens (opaque or JWTs) and needs to authenticate+authorize the end user. The token may also need to be exchanged when the application is doing REST client calls to another application.

- Add a partial OIDC mock based on OpenAPI artifacts
- This OpenAPI schema is not actually implemented 'as-is' by any known providers, so I used example.org as folder.
- I've kept most examples out of the primary schema, as I'm not sure how opinionated it should be given OIDC is a technical API.
- I've added a  README to act as a "userguide" 

/cc @lbroudoux @FroMage from discussions at RivieraJUG

### CODE REVIEW

**Comment by FroMage** [comment]
Interesting, but why not add a `/.well-known/openid-configuration` endpoint too? Otherwise I have to configure the paths, no?

**Comment by rquinio1A** [comment]
> Interesting, but why not add a `/.well-known/openid-configuration` endpoint too? Otherwise I have to configure the paths, no?

Actually I put the example for /.well-known/openid-configuration directly in the primary artifact https://github.com/microcks/microcks-quickstarters/blob/8a7c0ddb6d903a02fb56eec20a1209f697b4a6c2/oidc/example.com/oidc-1.0-openapi.yaml#L24

**Review by lbroudoux — APPROVED** [review]
Awesome! Thna you very much @rquinio1A!

**Comment by lbroudoux** [comment]
This is a great work! Thank you @rquinio1A

As you called this one `example.com,` what do you think about creating other OIDC implementation mocks and complementing this work with `github.com,` `x.com,`... ?
Once packaged for https://hub.microcks.io, we could have an `OpenID Connect` API package with different API/versions corresponding to multiple vendors.

@FroMage: As you have worked on this topic, would you have links to reference documentation or OpenAPI stubs for the different vendors? I'd like to give it a try and see if we can easily translate that material into OpenAPI + examples like is has been done by @rquinio1A

**Comment by rquinio1A** [comment]
You're welcome!
I'm not familiar enough in the differences between OIDC providers. They have different URLs/paths but that's a bit irrelevant with the discovery. I've also seen custom claims in JWTs, but not sure if it would impact the spec/mock.

**Comment by lbroudoux** [comment]
Thank you!

**Comment by lbroudoux** [comment]
Hey @rquinio1A and @FroMage,

I've added a second OIDC mock for GitHub OIDC flow. You can find it here: https://github.com/microcks/microcks-quickstarters/tree/main/oidc/github.com in case you want to give it a try!

**Pull request merged**
